//go:build n1ql

//  Copyright (c) 2026 Couchbase, Inc.
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the
//  License. You may obtain a copy of the License at
//  http://www.apache.org/licenses/LICENSE-2.0
//  Unless required by applicable law or agreed to in writing,
//  software distributed under the License is distributed on an "AS
//  IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
//  express or implied. See the License for the specific language
//  governing permissions and limitations under the License.

package test

// TestFlatRootWithCompiler proves the flat-root "fake it" path works through the
// COMPILER, not just the interpreter: it convs/emits queries over the synthetic
// default:flatpeople keyspace (a flat root -- record files directly under
// test/data/flatpeople, no ns/keyspace subdirs) into test/tmp, where the generated
// tests run the baked ops against a flat-root store (SetupCompiledFlatRoot) and
// compare to the interpreter oracle. Same generate->compile->run->compare flow
// as TestQueryCasesWithCompiler.

import (
	"fmt"
	"io/ioutil"
	"strings"
	"testing"

	"github.com/couchbase/n1k1/glue"
	"github.com/couchbase/n1k1/glue/emit"
)

func TestFlatRootWithCompiler(t *testing.T) {
	// The flat-root store: test/data/flatpeople opened as its own root => the wrapper
	// advertises a synthetic default:flatpeople keyspace.
	store, err := glue.FileStore("./data/flatpeople")
	if err != nil {
		t.Fatalf("FileStore(flatpeople): %v", err)
	}
	store.InitParser()

	cases := []struct{ name, stmt string }{
		{"FlatScan", `SELECT p.id AS id FROM flatpeople AS p`},
		{"FlatCount", `SELECT COUNT(*) AS n FROM flatpeople`},
		{"FlatGroup", `SELECT p.team AS team, COUNT(*) AS n FROM flatpeople AS p GROUP BY p.team`},
	}

	type genCase struct {
		about    string
		stmt     string
		labels   []string
		expected string
		lines    []string
	}
	var gen []genCase
	var skipped []string

	for _, fc := range cases {
		conv := convOf(store, "", fc.stmt)
		if conv == nil {
			skipped = append(skipped, fc.name+" (unconvertible)")
			continue
		}
		if usesUnbridgedOp(conv.TopOp) || !stringifyExprTrees(conv.TopOp) ||
			!allDatastoreOpsBakeable(conv.TopOp) {
			skipped = append(skipped, fc.name+" (not bakeable)")
			continue
		}
		got, runErr := n1k1RunStatement(store, fc.stmt)
		if runErr != nil {
			t.Fatalf("interpreter %s: %v", fc.name, runErr)
		}
		gen = append(gen, genCase{
			about:    fc.name + ": " + oneLine(fc.stmt),
			stmt:     fc.stmt,
			labels:   conv.TopOp.Labels,
			expected: "[" + strings.Join(got, ",") + "]",
			lines:    emit.OpToLines(conv.TopOp),
		})
	}

	var allLines strings.Builder
	for _, g := range gen {
		for _, ln := range g.lines {
			allLines.WriteString(ln)
		}
	}
	emitted := allLines.String()

	c := []string{
		"//go:build n1ql",
		``,
		"// Code generated by TestFlatRootWithCompiler. DO NOT EDIT.",
		``,
		"package tmp",
		``,
		`import "testing"`,
		`import "github.com/couchbase/n1k1/base"`,
		`import "github.com/couchbase/n1k1/glue"`,
		`import "github.com/couchbase/n1k1/test"`,
	}
	for _, oi := range emit.OptionalImports {
		if strings.Contains(emitted, oi.Qualifier) {
			c = append(c, fmt.Sprintf("import %q", oi.Path))
		}
	}
	c = append(c, ``, "var _ = glue.ExprStr", "var _ = base.Labels(nil)", ``)

	for i, g := range gen {
		c = append(c, "// ------------------------------------------")
		c = append(c, "// "+g.about)
		c = append(c, fmt.Sprintf("func TestGeneratedFR_%d(t *testing.T) {", i))
		c = append(c, `  lzVars, lzYieldVals, lzYieldErr, returnYields, cleanup :=`)
		c = append(c, fmt.Sprintf(`    test.SetupCompiledFlatRoot(t, %q)`, g.stmt))
		c = append(c, "  defer cleanup()")
		c = append(c, "  _ = lzVars")
		c = append(c, "  _ = lzYieldVals")
		c = append(c, "  _ = lzYieldErr")
		c = append(c, "")
		c = append(c, g.lines...)
		c = append(c, "")
		c = append(c, fmt.Sprintf("  test.CheckCompiledRows(t, %#v, returnYields(), %q, %q)",
			g.labels, g.expected, g.about))
		c = append(c, "}\n")
	}

	if err := ioutil.WriteFile("./tmp/generated_by_flat_compiler_test.go",
		[]byte(strings.Join(c, "\n")), 0644); err != nil {
		t.Fatal(err)
	}
	// t.Logf("flat-root compiler: emitted=%d skipped=%v", len(gen), skipped)
}
