//go:build n1ql

//  Copyright (c) 2026 Couchbase, Inc.
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the
//  License. You may obtain a copy of the License at
//  http://www.apache.org/licenses/LICENSE-2.0
//  Unless required by applicable law or agreed to in writing,
//  software distributed under the License is distributed on an "AS
//  IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
//  express or implied. See the License for the specific language
//  governing permissions and limitations under the License.

package test

// TestQueryCasesWithCompiler runs the local data-driven queryCases (LET / WITH /
// LETTING / subqueries -- see cases_test.go) through the n1k1 COMPILER, the same
// generate -> compile -> run -> compare flow as TestSuiteWithCompiler but over
// the test/data store. Each convertible case is emitted as fused Go into
// test/tmp; the compiled output is compared against the interpreter's result (a
// differential oracle: the compiled query must produce what the interpreter does,
// which cases_test.go already checks for correctness).

import (
	"fmt"
	"io/ioutil"
	"strings"
	"testing"

	"github.com/couchbase/n1k1/base"
	"github.com/couchbase/n1k1/glue"
	"github.com/couchbase/n1k1/test/emit"
)

func TestQueryCasesWithCompiler(t *testing.T) {
	store, err := glue.FileStore("./") // test/ ; "data:" -> test/data
	if err != nil {
		t.Fatalf("FileStore: %v", err)
	}
	store.InitParser()

	type genCase struct {
		about    string
		stmt     string
		labels   base.Labels
		expected string // interpreter result as a JSON array
		lines    []string
	}
	var gen []genCase
	var skipped []string

	for _, qc := range queryCases {
		// Convert with namespace "" (as testFileStoreSelect / SetupCompiledData
		// do) so the baked datastore Temps line up at compiled runtime.
		conv := convOf(store, "", qc.stmt)
		if conv == nil {
			skipped = append(skipped, qc.name+" (unconvertible)")
			continue
		}
		if usesUnbridgedOp(conv.TopOp) {
			skipped = append(skipped, qc.name+" (unbridged op)")
			continue
		}
		if !stringifyExprTrees(conv.TopOp) {
			skipped = append(skipped, qc.name+" (exprTree not serializable)")
			continue
		}
		if !allDatastoreOpsBakeable(conv.TopOp) {
			skipped = append(skipped, qc.name+" (datastore op not bakeable)")
			continue
		}

		// Oracle: the interpreter's rows for the same statement.
		got, runErr := n1k1RunStatement(store, qc.stmt)
		if runErr != nil {
			t.Fatalf("interpreter %s: %v", qc.name, runErr)
		}

		gen = append(gen, genCase{
			about:    qc.name + ": " + oneLine(qc.stmt),
			stmt:     qc.stmt,
			labels:   conv.TopOp.Labels,
			expected: "[" + strings.Join(got, ",") + "]",
			lines:    emit.OpToLines(conv.TopOp),
		})
	}

	var allLines strings.Builder
	for _, g := range gen {
		for _, ln := range g.lines {
			allLines.WriteString(ln)
		}
	}
	emitted := allLines.String()

	c := []string{
		"//go:build n1ql",
		``,
		"// Code generated by TestQueryCasesWithCompiler. DO NOT EDIT.",
		``,
		"package tmp",
		``,
		`import "testing"`,
		`import "github.com/couchbase/n1k1/base"`,
		`import "github.com/couchbase/n1k1/glue"`,
		`import "github.com/couchbase/n1k1/test"`,
	}
	for _, oi := range emit.OptionalImports {
		if strings.Contains(emitted, oi.Qualifier) {
			c = append(c, fmt.Sprintf("import %q", oi.Path))
		}
	}
	c = append(c, ``, "var _ = glue.ExprStr", "var _ = base.Labels(nil)", ``)

	for i, g := range gen {
		c = append(c, "// ------------------------------------------")
		c = append(c, "// "+g.about)
		c = append(c, fmt.Sprintf("func TestGeneratedQC_%d(t *testing.T) {", i))
		c = append(c, `  lzVars, lzYieldVals, lzYieldErr, returnYields, cleanup :=`)
		c = append(c, fmt.Sprintf(`    test.SetupCompiledData(t, %q)`, g.stmt))
		c = append(c, "  defer cleanup()")
		c = append(c, "  _ = lzVars")
		c = append(c, "  _ = lzYieldVals")
		c = append(c, "  _ = lzYieldErr")
		c = append(c, "")
		c = append(c, g.lines...)
		c = append(c, "")
		c = append(c, fmt.Sprintf("  test.CheckCompiledRows(t, %#v, returnYields(), %q, %q)",
			g.labels, g.expected, g.about))
		c = append(c, "}\n")
	}

	err = ioutil.WriteFile("./tmp/generated_by_query_compiler_test.go",
		[]byte(strings.Join(c, "\n")), 0644)
	if err != nil {
		t.Fatal(err)
	}

	t.Logf("query-cases compiler: emitted=%d skipped=%v", len(gen), skipped)
}
